#!/usr/sbin/nft -f

flush ruleset

table inet filter {
        chain input {
                type filter hook input priority 0;policy accept;
        }
        chain forward {
                type filter hook forward priority 0;policy accept;
                iif "eth0" ip saddr 172.16.0.5 counter drop
        }
        chain output {
                type filter hook output priority 0;policy accept;
        }
}
