FROM ros:jazzy
ARG ROS_DISTRO=jazzy
ARG USERNAME=ros
ARG USER_UID=1000
ARG USER_GID=1000

RUN apt-get update && apt-get upgrade -y
RUN apt-get install -y  \
       gdb              \
       bash-completion  \
       cmake-curses-gui \
       rsync            \
       nano             \
       vim              \
       wget             \
       tmux             \
       tmuxinator       \
       iputils-ping     \
       keychain         

RUN apt-get install -y git  g++ libjpeg8-dev libpng-dev libglu1-mesa-dev libltdl-dev libfltk1.3-dev
RUN if id -u $USER_UID ; then userdel `id -un $USER_UID` ; fi

# Create the user
RUN groupadd --gid $USER_GID $USERNAME \
    && useradd --uid $USER_UID --gid $USER_GID -m $USERNAME \
    #
    # [Optional] Add sudo support. Omit if you don't need to install software after connecting.
    && apt-get update \
    && apt-get install -y sudo \
    && echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME \
    && chmod 0440 /etc/sudoers.d/$USERNAME
RUN usermod -a -G dialout $USERNAME
RUN usermod -a -G tty $USERNAME
RUN usermod -a -G video $USERNAME
RUN mkdir /home/$USERNAME/projects \
    && chown -R  $USERNAME:$USERNAME /home/$USERNAME/projects 
RUN apt-get update && apt-get upgrade -y

RUN git clone --depth=1 https://github.com/rtv/Stage.git /tmp/stage \
 && cmake -S /tmp/stage -B /tmp/stage/build -DCMAKE_BUILD_TYPE=Release \
 && cmake --build /tmp/stage/build -j$(nproc) \
 && cmake --install /tmp/stage/build \
 && ldconfig \
 && rm -rf /tmp/stage


WORKDIR /ws
# COPY ./ws/src/stage_ros2 /ws/src/stage_ros2
# COPY ./ws/src/fastdds/client /ws/src/fastdds/client

# RUN apt-get update && apt-get install -y python3-rosdep \
#     && rm -rf /var/lib/apt/lists/*
# RUN apt-get update && \
#     rosdep update && rosdep install --from-paths src --ignore-src -r -y

SHELL ["/bin/bash","-c"]
# RUN source /opt/ros/$ROS_DISTRO/setup.bash && colcon build --merge-install

ENV ROS_DOMAIN_ID=42 \
    ROS_AUTOMATIC_DISCOVERY_RANGE=LOCALHOST \
    LIBGL_ALWAYS_SOFTWARE=1

USER ${USERNAME}
WORKDIR /ws
CMD ["/bin/bash"]
