FROM ros:jazzy
ARG ROS_DISTRO=jazzy
ARG USERNAME=attacker
ARG USER_UID=1000
ARG USER_GID=1000

RUN apt-get update && apt-get upgrade -y
RUN apt-get install -y  \
       gdb              \
       bash-completion  \
       cmake-curses-gui \
       rsync            \
       nano             \
       vim              \
       wget             \
       tmux             \
       tmuxinator       \
       iputils-ping     \
       keychain         

RUN if id -u $USER_UID ; then userdel `id -un $USER_UID` ; fi

# Create the user
RUN groupadd --gid $USER_GID $USERNAME \
    && useradd --uid $USER_UID --gid $USER_GID -m $USERNAME 
    #
    # # [Optional] Add sudo support. Omit if you don't need to install software after connecting.
    # && apt-get update \
    # && apt-get install -y sudo \
    # && echo $USERNAME ALL=(root) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME \
    # && chmod 0440 /etc/sudoers.d/$USERNAME
RUN usermod -a -G dialout $USERNAME
RUN usermod -a -G tty $USERNAME
RUN usermod -a -G video $USERNAME
RUN mkdir /home/$USERNAME/projects \
    && chown -R  $USERNAME:$USERNAME /home/$USERNAME/projects 
RUN apt-get update && apt-get upgrade -y

RUN apt-get update && apt-get install -y \
    ros-jazzy-tf2-ros dsniff nftables net-tools ros-jazzy-tf2-ros ros-jazzy-filters ros-jazzy-laser-filters ros-jazzy-pluginlib ros-jazzy-tuw-geometry libcap2-bin


WORKDIR /ws
RUN mkdir -p /ws/src/logs && chmod 777 /ws/src/logs



SHELL ["/bin/bash","-c"]
RUN source /opt/ros/$ROS_DISTRO/setup.bash && colcon build --merge-install
RUN echo "source /opt/ros/$ROS_DISTRO/setup.bash" >> /home/$USERNAME/.bashrc
RUN echo "source /ws/install/setup.bash" >> /home/$USERNAME/.bashrc
RUN setcap cap_net_raw,cap_net_admin+ep "$(which arpspoof)" && getcap "$(which arpspoof)"
RUN setcap cap_net_admin+ep "$(which nft)" && getcap "$(which nft)"

ENV ROS_DOMAIN_ID=42 \
    ROS_AUTOMATIC_DISCOVERY_RANGE=LOCALHOST

USER ${USERNAME}
WORKDIR /ws
CMD ["/bin/bash"]