FROM ros:jazzy
ARG ROS_DISTRO=jazzy
ARG USERNAME=dev
ARG USER_UID=1000
ARG USER_GID=1000

RUN apt-get update && apt-get upgrade -y
RUN apt-get install -y \
       gdb \
       bash-completion \
       build-essential \
       cmake-curses-gui \
       rsync \
       nano \
       vim \
       wget \
       tmux \
       git \
       python3-rosdep \
       python3-colcon-common-extensions \
       iputils-ping


RUN if id -u $USER_UID ; then userdel `id -un $USER_UID` ; fi

# Create the user
RUN groupadd --gid $USER_GID $USERNAME \
    && useradd --uid $USER_UID --gid $USER_GID -m $USERNAME \
    #
    # [Optional] Add sudo support. Omit if you don't need to install software after connecting.
    && apt-get update \
    && apt-get install -y sudo \
    && echo $USERNAME ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/$USERNAME \
    && chmod 0440 /etc/sudoers.d/$USERNAME
RUN usermod -a -G dialout $USERNAME
RUN usermod -a -G tty $USERNAME
RUN usermod -a -G video $USERNAME
RUN mkdir /home/$USERNAME/projects \
    && chown -R  $USERNAME:$USERNAME /home/$USERNAME/projects 
RUN apt-get update && apt-get upgrade -y
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        python3-rosdep

USER ${USERNAME}
WORKDIR /ws


RUN echo "source /opt/ros/${ROS_DISTRO}/setup.bash" >> /home/${USERNAME}/.bashrc && \
    echo "source /ws/install/setup.bash" >> /home/$USERNAME/.bashrc 


CMD ["/bin/bash"]